[tool.ruff]
line-length = 120
lint.extend-select = [
    "B",
    "BLE",
    "C4",
    "ERA",
    "I",
    "ICN",
    # "INP",
    "ISC",
    "N",
    "PGH",
    "PIE",
    # "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "T20",
    "TCH",
    "TID",
    "YTT",
]
lint.ignore = ["TCH0"]
show-fixes = true
output-format = "concise"

[tool.pylint]
max-line-length = 120
