[project]
name = "moeviusbot"
dynamic = ["version"]
requires-python = ">=3.13"

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
lint.extend-select = ["ALL"]
lint.ignore = ["COM812", "D", "EXE002"]
show-fixes = true
output-format = "concise"

[tool.pylint]
max-line-length = 120
