[tool.black]
line-length = 120
target-version = ["py312"]

[tool.ruff]
line-length = 120
lint.extend-select = ["ALL"]
lint.ignore = ["ANN101", "COM812", "D", "EXE002"]
show-fixes = true
output-format = "concise"

[tool.pylint]
max-line-length = 120
